In [1]:
import tensorflow as tf
import numpy as np

# What is a tensor? 

Rank 0 tensor: **scalar** (e.g. 5)

Rank 1 tensor: **vector** (e.g. \begin{pmatrix}1 \\ 2 \\ 3 \end{pmatrix}


Rank 2 tensor: **matrix** (e.g. \begin{bmatrix}1 \ 2 \ 3 \\ 4 \ 5 \ 6 \\ 7 \ 8 \ 9 \end{bmatrix}

Rank 3 tensor: e.g. **image** with dimensions width * height * color channels

Rank 4 tensor: e.g. RGB video with dimensions time, width, height, color channels

Rank 5 tensor: e.g. batch of RGB videos with dimensions batch_size, time, width, height, color channels

.
.
.

# Creating tensors from other objects in Python

In [2]:
to_tensor = 5.0

#to_tensor = [ [1,2,3] , [4,5,6] ]

#to_tensor = np.arange(1,7)

#to_tensor = np.ones((2,3))

#to_tensor = np.random.randn(2,3)


tensor = tf.constant(to_tensor, 
                     dtype=tf.float32
                    )

print(tensor)

tf.Tensor(5.0, shape=(), dtype=float32)


2021-10-31 12:07:43.041319: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-31 12:07:43.042047: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-31 12:07:43.074197: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-31 12:07:43.074893: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-31 12:07:43.075629: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from S

# Creating tensors directly with Tensorflow

In [3]:
tensor = tf.ones(shape=(3,2))

print(tensor)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# Reshaping and transposing tensors

In [16]:
tensor = tf.range(1,101, dtype=tf.float32)
print(tensor.shape, "\n")

# reshaping
reshaped_tensor = tf.reshape(tensor, (5,10,2))
print(reshaped_tensor.shape, "\n")

# adding a dimension of 1: e.g. from tensor shape (32,10) -> (32,10,1)
expanded_tensor = tf.expand_dims(tensor, axis=0)
print(expanded_tensor.shape, "\n")

# removing dimensions of 1: e.g. (1,20,20) -> (20,20)
squeezed_tensor = tf.squeeze(expanded_tensor, axis=None)
print(squeezed_tensor.shape, "\n")

# transposing
transposed_tensor = tf.transpose(reshaped_tensor)
print(transposed_tensor.shape, "\n")

# transposing with permutation: e.g. (10,5,2) -> (5,10,2)
permuted_tensor = tf.transpose(reshaped_tensor, [0,1,2])
print(permuted_tensor.shape)

(100,) 

(5, 10, 2) 

(1, 100) 

(100,) 

(2, 10, 5) 

(5, 10, 2)


# Matrix multiplication and other operations with tensors

In [5]:
A = tf.ones((1,5))
B = tf.ones((5,10))

result = tf.matmul(A,B)
print(result)

tf.Tensor([[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]], shape=(1, 10), dtype=float32)


2021-10-31 12:07:44.621574: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


In [6]:
# element-wise operations

A = tf.range(1,6, dtype=tf.float32)
B = tf.ones((5))*0.5
print(B**A)

tf.Tensor([0.5     0.25    0.125   0.0625  0.03125], shape=(5,), dtype=float32)


# Concatenating tensors

In [7]:
A = tf.ones((128,12,12,15), dtype=tf.float32)

B = tf.zeros((128,12,12,35), dtype=tf.float32)


tf.concat([A,B], axis= -1)


<tf.Tensor: shape=(128, 12, 12, 50), dtype=float32, numpy=
array([[[[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.]],

        [[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.]],

        [[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.]],

        ...,

        [[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ...

# Stacking tensors

In [8]:
A = tf.ones((32,15,7), dtype=tf.float32)

B = tf.zeros((32,15,7), dtype=tf.float32)

tf.stack([A,B], axis=0)

<tf.Tensor: shape=(2, 32, 15, 7), dtype=float32, numpy=
array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1

# Constants and variables

- Tensors can be constants or variables

- Constants should be used for data, variables for model parameters

- Variables can be trainable or non-trainable

In [9]:
var = tf.Variable([1,2,3], trainable = True, dtype=tf.float32, name="weight_1")
print(var)

<tf.Variable 'weight_1:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>


In [10]:
var.assign([2,3,4])
print(var)

<tf.Variable 'weight_1:0' shape=(3,) dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>


# Converting current variable values to a constant tensor

- Can be useful for keeping track of model parameters during training

In [11]:
stored_tensor = tf.convert_to_tensor(var)

In [12]:
print(stored_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


# Reduce-operations in tensorflow

- instead of sum, we use reduce_sum and specify the axis over which we want to sum.
- same for other operations like reduce_mean

In [13]:
tensor = tf.ones((32,4,1))
print(tensor.shape,"\n")

feature_sum = tf.reduce_sum(tensor, axis=1)
print(feature_sum.shape, "\n")

batch_sum = tf.reduce_sum(tensor, axis=0)
print(batch_sum.shape, "\n")

total_sum = tf.reduce_sum(tensor, axis=None)
print(total_sum.shape)

(32, 4, 1) 

(32, 1) 

(4, 1) 

()
