In [ ]:
import tensorflow as tf
import numpy as np

# only use 1GB of GPU (allows having multiple notebooks open simultaneously)
gpus = tf.config.list_physical_devices('GPU')
if gpus:
  # Restrict TensorFlow to only allocate 1GB of memory on the first GPU
  try:
    tf.config.set_logical_device_configuration(
        gpus[0],
        [tf.config.LogicalDeviceConfiguration(memory_limit=1024)])
    logical_gpus = tf.config.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Virtual devices must be set before GPUs have been initialized
    print(e)

# What is a tensor? 

- **Tensors are generalizations of scalars, vectors and matrices**

Rank 0 tensor: **scalar** with shape () e.g. 5

Rank 1 tensor: **vector** with shape (n) e.g. \begin{pmatrix}1 \\ 2 \\ 3 \end{pmatrix}


Rank 2 tensor: **matrix** with shape (m,n) e.g. \begin{bmatrix}1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}

Rank 3 tensor: e.g. **image** with shape (width, height, color channels)

Rank 4 tensor: e.g. RGB video with shape (time, width, height, color channels)

Rank 5 tensor: e.g. batch of RGB videos with shape (batch_size, time, width, height, color channels)

.
.
.

# Creating tensors from other objects in Python

In [6]:
to_tensor = 5.0

#to_tensor = [ [1,2,3], [4,5,6] ]

#to_tensor = np.arange(1,7)

#to_tensor = np.ones((2,3))

#to_tensor = np.random.randn(5,2,3)


tensor = tf.constant(to_tensor, 
                     dtype=tf.float32
                    )
print(tensor)

tf.Tensor(
[[[ 1.0884721   0.01038556 -1.3678032 ]
  [ 1.8345412  -1.0320939   0.02609846]]

 [[ 1.0184101   1.0912756   1.8569536 ]
  [-0.3802737  -2.2863107  -0.10352949]]

 [[-0.23382793  0.37886629  1.0061024 ]
  [-1.4144685  -0.7937287  -1.3743494 ]]

 [[ 0.93307203 -0.4487751  -0.01279868]
  [ 0.5661924   0.7984559   0.76580685]]

 [[ 1.1742547  -0.2779196   0.02690826]
  [-0.4450057   0.09467939 -1.1013812 ]]], shape=(5, 2, 3), dtype=float32)


# Creating tensors directly with Tensorflow

In [12]:
tensor = tf.ones(shape=(3,2))

#tensor = tf.random.normal((3,2))

# generate tensor filled with random integers
#tensor = tf.random.uniform((4,3,2), minval= 0, maxval=100, dtype=tf.int32)

print(tensor)

tf.Tensor(
[[[83 86]
  [ 5 26]
  [28 18]]

 [[11  4]
  [27 15]
  [63 47]]

 [[38 27]
  [31 25]
  [78 97]]

 [[18 31]
  [75 57]
  [ 1 59]]], shape=(4, 3, 2), dtype=int32)


# Reshaping and transposing tensors

In [13]:
tensor = tf.range(1,101, dtype=tf.float32)
print(tensor.shape, "\n")

# reshaping
reshaped_tensor = tf.reshape(tensor, (20,5))
print(reshaped_tensor.shape, "\n")

# adding a dimension of 1: e.g. from tensor shape (32,10) -> (32,10,1)
expanded_tensor = tf.expand_dims(tensor, axis=-1)
print(expanded_tensor.shape, "\n")

# removing dimensions of 1: e.g. (1,20,1,1,20) -> (20,20)
squeezed_tensor = tf.squeeze(expanded_tensor, axis=None)
print(squeezed_tensor.shape, "\n")

# transposing

transposed_tensor = tf.transpose(reshaped_tensor)
print(transposed_tensor.shape, "\n")

# transposing with permutation: e.g. (10,5,2) -> (5,10,2)
permuted_tensor = tf.transpose(reshaped_tensor, perm=[1,0])
print(permuted_tensor.shape)

(100,) 

(20, 5) 

(100, 1) 

(100,) 

(5, 20) 

(5, 20)


# Concatenating tensors

In [14]:
A = tf.ones((128,12,12,15), dtype=tf.float32)

B = tf.zeros((128,12,12,35), dtype=tf.float32)


tf.concat([A,B], axis= -1)


<tf.Tensor: shape=(128, 12, 12, 50), dtype=float32, numpy=
array([[[[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.]],

        [[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.]],

        [[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.]],

        ...,

        [[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ...

# Stacking tensors

In [18]:
A = tf.ones((32,15,7), dtype=tf.float32)

B = tf.zeros((32,15,7), dtype=tf.float32)

tf.stack([A,B]*5, axis=0)

<tf.Tensor: shape=(10, 32, 15, 7), dtype=float32, numpy=
array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 

# Reduce-operations in tensorflow

- instead of sum, we use reduce_sum and specify the axis over which we want to sum.
- same for other operations like mean, std, product etc.

In [20]:
tensor = tf.ones((32,4,1))
print(tensor.shape,"\n")

feature_sum = tf.reduce_sum(tensor, axis=1)
print(feature_sum.shape, "\n")

batch_sum = tf.reduce_prod(tensor, axis=0)
print(batch_sum.shape, "\n")

total_sum = tf.reduce_mean(tensor, axis=None)
print(total_sum.shape)

(32, 4, 1) 

(32, 1) 

(4, 1) 

()


# Matrix multiplication and other operations with tensors

In [24]:
A = tf.ones((1,5))
B = tf.ones((5,10))

#result = tf.matmul(A,B)
#print(result)

# generalized matmul for higher ranked tensors
result = tf.tensordot(A,B,axes=[1,0])
print(result)

tf.Tensor([[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]], shape=(1, 10), dtype=float32)


In [28]:
# element-wise operations

A = tf.range(1,6, dtype=tf.float32)
B = tf.ones(A.shape)*0.5
print(B**A)

tf.Tensor([0.5     0.25    0.125   0.0625  0.03125], shape=(5,), dtype=float32)


# Constants and variables

- Tensors can be constants or variables

- Constants should be used for data, variables for model parameters

- Variables can be trainable or non-trainable

In [29]:
var = tf.Variable([1,2,3], trainable = True, dtype=tf.float32, name="weight_1")
print(var)

<tf.Variable 'weight_1:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>


In [30]:
var.assign([2,3,4])
print(var)

<tf.Variable 'weight_1:0' shape=(3,) dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>


# Converting current variable values to a constant tensor

- Can be useful for keeping track of model parameters during training

In [31]:
stored_tensor = tf.convert_to_tensor(var)

In [32]:
print(stored_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


# Converting tensors to a different dtype

In [37]:
# before transforming, we have float32
print(stored_tensor.dtype)

tf.cast(stored_tensor, dtype=tf.int8)

<dtype: 'float32'>


<tf.Tensor: shape=(3,), dtype=int8, numpy=array([2, 3, 4], dtype=int8)>