In [1]:
import tensorflow as tf
import numpy as np

# What is a tensor? 

Rank 0 tensor: **scalar** (e.g. 5)

Rank 1 tensor: **vector** (e.g. \begin{pmatrix}1 \\ 2 \\ 3 \end{pmatrix}


Rank 2 tensor: **matrix** (e.g. \begin{bmatrix}1 \ 2 \ 3 \\ 4 \ 5 \ 6 \\ 7 \ 8 \ 9 \end{bmatrix}

Rank 3 tensor: e.g. **image** with dimensions width * height * color channels

Rank 4 tensor: e.g. RGB video with dimensions time, width, height, color channels

Rank 5 tensor: e.g. batch of RGB videos with dimensions batch_size, time, width, height, color channels

.
.
.

# Creating tensors from other objects in Python

In [165]:
to_tensor = 5.0

#to_tensor = [ [1,2,3] , [4,5,6] ]

#to_tensor = np.arange(1,7)

#to_tensor = np.ones((2,3))

#to_tensor = np.random.randn(2,3)


tensor = tf.constant(to_tensor, 
                     dtype=tf.float32
                    )

print(tensor)

tf.Tensor(5.0, shape=(), dtype=float32)


# Creating tensors directly with Tensorflow

In [113]:
tensor = tf.ones(shape=(3,2))

print(tensor)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# Reshaping and transposing tensors

In [141]:
tensor = tf.range(1,101, dtype=tf.float32)
print(tensor, "\n")

# reshaping
reshaped_tensor = tf.reshape(tensor, (5,10,2))
print(reshaped_tensor, "\n")

# transposing
transposed_tensor = tf.transpose(reshaped_tensor)
print(transposed_tensor, "\n")

# transposing with permutation

permuted_tensor = tf.transpose(reshaped_tensor, [0,1,2])
print(permuted_tensor)

tf.Tensor(
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.], shape=(100,), dtype=float32) 

tf.Tensor(
[[[  1.   2.]
  [  3.   4.]
  [  5.   6.]
  [  7.   8.]
  [  9.  10.]
  [ 11.  12.]
  [ 13.  14.]
  [ 15.  16.]
  [ 17.  18.]
  [ 19.  20.]]

 [[ 21.  22.]
  [ 23.  24.]
  [ 25.  26.]
  [ 27.  28.]
  [ 29.  30.]
  [ 31.  32.]
  [ 33.  34.]
  [ 35.  36.]
  [ 37.  38.]
  [ 39.  40.]]

 [[ 41.  42.]
  [ 43.  44.]
  [ 45.  46.]
  [ 47.  48.]
  [ 49.  50.]
  [ 51.  52.]
  [ 53.  54.]
  [ 55.  56.]
  [ 57.  58.]
  [ 59.  60.]]

 [[ 61.  62

# Matrix multiplication and other operations with tensors

In [151]:
A = tf.ones((1,5))
B = tf.ones((5,10))

result = tf.matmul(A,B)
print(result)

tf.Tensor([[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]], shape=(1, 10), dtype=float32)


In [164]:
# element-wise operations

A = tf.range(1,6, dtype=tf.float32)
B = tf.ones((5))*0.5
print(B**A)

tf.Tensor([0.5     0.25    0.125   0.0625  0.03125], shape=(5,), dtype=float32)


# Concatenating tensors

In [172]:
A = tf.ones((128,12,12,15), dtype=tf.float32)

B = tf.zeros((128,12,12,35), dtype=tf.float32)


tf.concat([A,B], axis= -1)


<tf.Tensor: shape=(128, 12, 12, 50), dtype=float32, numpy=
array([[[[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.]],

        [[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.]],

        [[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.]],

        ...,

        [[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ...

# Stacking tensors

In [178]:
A = tf.ones((32,15,7), dtype=tf.float32)

B = tf.zeros((32,15,7), dtype=tf.float32)

tf.stack([A,B], axis=0)

<tf.Tensor: shape=(2, 32, 15, 7), dtype=float32, numpy=
array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1

# Constants and variables

- Tensors can be constants or variables

- Constants should be used for data, variables for model parameters

- Variables can be trainable or non-trainable

In [207]:
var = tf.Variable([1,2,3], trainable = True, dtype=tf.float32, name="weight_1")
print(var)

<tf.Variable 'weight_1:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>


In [208]:
var.assign([2,3,4])
print(var)

<tf.Variable 'weight_1:0' shape=(3,) dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>


# Converting current variable values to a constant tensor

- Can be useful for keeping track of model parameters during training

In [201]:
stored_tensor = tf.convert_to_tensor(var)

In [202]:
print(stored_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
